kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codegen12d-sep17-2-vllm-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: codegen12d-sep17-2-vllm-dsp-job
    namespace: codegen12d-sep17-2-vllm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codegen12d-sep17-2-vllm-dsp-job-role