apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codegen12d-sep17-2-vllm
  janus-idp.io/tekton: codegen12d-sep17-2-vllm
  backstage.io/kubernetes-id: codegen12d-sep17-2-vllm
  backstage.io/kubernetes-namespace: codegen12d-sep17-2-vllm 
  app.kubernetes.io/part-of: codegen12d-sep17-2-vllm
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- rhoai/
