apiVersion: v1
kind: ConfigMap
metadata:
  name: codegen12d-sep17-2-vllm-model-config
data:
  MODEL_ENDPOINT: "http://codegen12d-sep17-2-vllm-model-server:8001"
  MODEL_NAME: "Nondzu/Mistral-7B-code-16k-qlora"