apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: codegen12d-sep17-2-vllm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen12d-sep17-2-vllm 
  name: codegen12d-sep17-2-vllm
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: codegen12d-sep17-2-vllm 
    weight: 100 
  wildcardPolicy: None
