apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: codegen12d-sep17-2-vllm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen12d-sep17-2-vllm 
  name: codegen12d-sep17-2-vllm
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: codegen12d-sep17-2-vllm 
