apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: codegen12d-sep17-2-vllm-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen12d-sep17-2-vllm-database 
  name: codegen12d-sep17-2-vllm-database
spec:
  ports:
  - port: 
    protocol: TCP
    targetPort: 
  selector:
    app.kubernetes.io/instance: codegen12d-sep17-2-vllm-database 
